### PR TITLE
147 capture datawolf logs

### LINKED ISSUE #147: capture datawolf logs
At each step datawolf has a stdout dataset. e.g. 
```
"stdout": "4eebb9b8-43f3-45cb-800c-d717d07d5d30",
```

We can offer download, aggregate and preview them in the app:
- Write a new widget for displaying logs. Plain text would be enough. Can use the \<dl\> \<dt\> tag maybe (Can reuse some the code and style from clowder v2's log widget?)
- Code those ids in datawolf.config.js (@longshuicy )
- connect with the widget
- Display the entry in viewResultEntryTable.jsx

### PR DESCRIPTION
**Pull request by longshuicy**
@ywkim312 @Vismayak @navarroc 
Login as yourself and see the logs for each execution at step 3-4. Only admins (incore_ncsa group have this availalbe)

image
image

### CODE REVIEW

**Comment by ywkim312** [comment]
I don't see anything logged in as myself. Maybe because I never performed any execution myself? I was able to see something after changing it to view all

**Comment by ywkim312** [comment]
I can see log 
image
I approve

**Review by ywkim312 — APPROVED** [review]

**Comment by longshuicy** [comment]
hmm you should see other people's logs too. You sure you are on this branch?

**Comment by longshuicy** [comment]
great!

**Pull request merged**
