### PR TITLE
Test publish gh action

### LINKED ISSUE #283: Publish to github registry failed
Need to reinvestigate why they are failed
https://github.com/IN-CORE/incore-playbook/actions/workflows/publish.yaml

### PR DESCRIPTION
**Pull request by longshuicy**
The main change is in publish github action:
- There is no need to `npm install` or `npm build` before publish
- But we need to properly set the .npmrc to point to github repo, plus the token

There shouldn't be any change need in the package.json. My IDE is having some reformatting setting; I can revert that part given more time.

To Test:
- See the successful github action here https://github.com/IN-CORE/incore-playbook/actions/runs/7994958276/job/21834199591
- See there is the 0.0.1 version published https://github.com/IN-CORE/incore-playbook/pkgs/npm/incore-playbook/181885553
- Install 0.0.1 with either of the testbed playbooks (e.g. Galveston-Playbook) and run `npm run start: dev`
```
"dependencies": {
		"@in-core/incore-playbook": "npm:@in-core/incore-playbook@^0.0.1",
		"@material-ui/core": "^4.11.0",
		...
```

### CODE REVIEW

**Comment by ywkim312** [comment]
Is it okay we don't need to build? Then we don't need to worry about linting and others in publish. This is nice but it might be too good to be true

**Comment by longshuicy** [comment]
> Is it okay we don't need to build? Then we don't need to worry about linting and others in publish. This is nice but it might be too good to be true

Yes according to npm, there is no mention of build or install 
https://docs.npmjs.com/cli/v8/commands/npm-publish

P.S. There is a command to dry run test `npm publish --dry-run`

But that being said, i still think it's a good practice that we start to enforcing linting and have GH actions around checking linting. 
Not build per-se though, because this is the core library being used; Itself is not a react app hence no need to build

**Comment by ywkim312** [comment]
> > Is it okay we don't need to build? Then we don't need to worry about linting and others in publish. This is nice but it might be too good to be true
> 
> Yes according to npm, there is no mention of build or install https://docs.npmjs.com/cli/v8/commands/npm-publish
> 
> P.S. There is a command to dry run test `npm publish --dry-run`
> 
> But that being said, i still think it's a good practice that we start to enforcing linting and have GH actions around checking linting. Not build per-se though, because this is the core library being used; Itself is not a react app hence no need to build

Yes I tested npm publish in the local and it worked also build worked well in the local but failed in github action. So I fixed all the lintings and pakcages :)
If it is working like this, that is great and I have no objection =)

**Comment by longshuicy** [comment]
@ywkim312 i created a task for linting so we don't forget. https://github.com/IN-CORE/incore-playbook/issues/302

**Comment by ywkim312** [comment]
> @ywkim312 i created a task for linting so we don't forget. #302

My branch has the data that fixed all the linting problem. Can we use it somehow? Otherwise, we have to spend some hours again

**Comment by ywkim312** [comment]
> @ywkim312 i created a task for linting so we don't forget. #302

Also using eslint --fix didn't work

**Comment by longshuicy** [comment]
> > @ywkim312 i created a task for linting so we don't forget. #302
> 
> My branch has the data that fixed all the linting problem. Can we use it somehow? Otherwise, we have to spend some hours again

Could you add your branch to the other Issue then so it got preserved.

**Comment by ywkim312** [comment]
> > > @ywkim312 i created a task for linting so we don't forget. #302
> > 
> > 
> > My branch has the data that fixed all the linting problem. Can we use it somehow? Otherwise, we have to spend some hours again
> 
> Could you add your branch to the other Issue then so it got preserved.

As long as we don't remove it, it will be there but we want to merge it soon before other changes happen, otherwise, it will have lots of conflict and we might want to redo

**Review by ywkim312 — APPROVED** [review]

**Comment by longshuicy** [comment]
> > > > @ywkim312 i created a task for linting so we don't forget. #302
> > > 
> > > 
> > > My branch has the data that fixed all the linting problem. Can we use it somehow? Otherwise, we have to spend some hours again
> > 
> > 
> > Could you add your branch to the other Issue then so it got preserved.
> 
> As long as we don't remove it, it will be there but we want to merge it soon before other changes happen, otherwise, it will have lots of conflict and we might want to redo

- The "upgrading libraries part" on your PR we need to proceed with caution, because sometimes those break things
- The linting part is also tricky; we need to get all the developers using the same lint setting; otherwise when each individual contribute to the code base, this linting change will get messed up again.

**Comment by ywkim312** [comment]
> > > > > @ywkim312 i created a task for linting so we don't forget. #302
> > > > 
> > > > 
> > > > My branch has the data that fixed all the linting problem. Can we use it somehow? Otherwise, we have to spend some hours again
> > > 
> > > 
> > > Could you add your branch to the other Issue then so it got preserved.
> > 
> > 
> > As long as we don't remove it, it will be there but we want to merge it soon before other changes happen, otherwise, it will have lots of conflict and we might want to redo
> 
> * The "upgrading libraries part" on your PR we need to proceed with caution, because sometimes those break things
> * The linting part is also tricky; we need to get all the developers using the same lint setting; otherwise when each individual contribute to the code base, this linting change will get messed up again.

Okay then maybe let's ditch the branch and make it from the scratch again

**Comment by longshuicy** [comment]
We will try it as a part of the precommit hook issue #302

**Pull request merged**
