### PR TITLE
57 datawolf status running not showing

### LINKED ISSUE #57: datawolf status running not showing
when there are steps running; it still says waiting...

stepState
: 
{17b23575-6394-4d5d-9a38-0a421d045ff0: "FINISHED", a4304865-81bc-49a0-fe67-6db2a5b2bd4e: "FINISHED",…}
2f136ed6-7b53-4c13-adaf-afd6f08b802d
: 
"WAITING"
3a166494-6285-4488-904c-674bc87a85bc
: 
"FINISHED"
17b23575-6394-4d5d-9a38-0a421d045ff0
: 
"FINISHED"
a4304865-81bc-49a0-fe67-6db2a5b2bd4e
: 
"FINISHED"
aa0d6301-5fab-476f-9d19-8741586f83f6
: 
"RUNNING"
ab2964ea-a93c-4453-b754-b39cb7f42d93
: 
"FINISHED"
dfd3bbb2-1ab8-47c9-f2d6-f3fc793b12ac
: 
"WAITING"
e5ffabe3-4633-4c9a-acd9-9c5d94ec3be7
: 
"FINISHED"

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR depends on the previous PR as it contains changes from the previous PR. It fixes the bug of showing Waiting even when it is running or in another state. Now, it will work based on priority. `FAILED|ABORTED > RUNNING > QUEUED > WAITING > UNKNOWN > FINISHED > UNDEFINED`

### CODE REVIEW

**Comment by Rashmil-1999** [comment]
I made a mistake in branching out from the previous branch. I will not make this mistake in the future. You only need to look at the `ViewResult.jsx` file in `childComponents`

**Comment by Rashmil-1999** [comment]
https://github.com/IN-CORE/incore-playbook/pull/91/files#diff-5fe6a0ef7bf672db000b7f76a980fa1d540e6d70fc98876cde71c85a9f137a97
this file in particular

**Comment by longshuicy** [comment]
> I made a mistake in branching out from the previous branch. I will not make this mistake in the future. You only need to look at the `ViewResult.jsx` file in `childComponents`

The logic is working. But in that case can I change this branch to target your previous branch? this way no messy git histories

**Review by longshuicy — APPROVED** [review]
@Rashmil-1999 i cleaned up merge conflicts and point this to your branch 77. If it look ok to you i can merge.

Then i will review PR 77

**Review by longshuicy — APPROVED** [review]

**Pull request merged**
