### PR TITLE
enable downloading inventories

### LINKED ISSUE #112: Download shapefiles instead of just csv
especially those in JSON format; find a way to turn into tabular data
Also check if possible we allow them download shapefiles

### PR DESCRIPTION
**Pull request by longshuicy**
Ready to be reviewed:
image

### CODE REVIEW

**Comment by ywkim312** [comment]
It worked well. The only concern that I have is that, it just come up, if the file size is big, then the actual downloading will start after some time, then the user might thinks that download is not working and clicking it multiple times?

**Comment by longshuicy** [comment]
> It worked well. The only concern that I have is that, it just come up, if the file size is big, then the actual downloading will start after some time, then the user might thinks that download is not working and clicking it multiple times?

right... but not sure what would be a quick fix. Maybe we need to change the multi-part download to streaming?

**Comment by ywkim312** [comment]
> > It worked well. The only concern that I have is that, it just come up, if the file size is big, then the actual downloading will start after some time, then the user might thinks that download is not working and clicking it multiple times?
> 
> right... but not sure what would be a quick fix. Maybe we need to change the multi-part download to streaming?

I am not sure. Maybe we can discuss it in tomorrow's PR party

**Comment by longshuicy** [comment]
temporary solution: have a pop up window to remind user that download has begin and ask them to wait till it finishes

**Comment by longshuicy** [comment]
@Rashmil-1999 @navarroc  please review

**Review by ywkim312 — APPROVED** [review]
worked well! great job!

**Pull request merged**
