### PR TITLE
Feedback changes p2

### LINKED ISSUE #197: UI Changes as per feedback pt 2
Change sorting logic and create a new component for step 3-3 `View Created`

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR addresses the following issues
- Disable sorting and sort the order of hazards to put newly created ones first.

### CODE REVIEW

**Comment by longshuicy** [comment]
im going to temporarily close this PR.

**Comment by Vismayak** [comment]
@longshuicy why did you temporarily close it? I have pushed one small change (without which the site doesnt load) but after that it is good to merge

**Comment by longshuicy** [comment]
cuz we are not doing this on the frontend anymore.. we will do pagination on the backend

**Comment by Rashmil-1999** [comment]
I verified this PR now. This will fix the develop branch as well.

**Review by longshuicy — APPROVED** [review]

**Review by longshuicy — APPROVED** [review]

**Pull request merged**
