### PR TITLE
fix slc sector shock comparison

### LINKED ISSUE #474: SLC capital shock comparison not working
image

Suspect that the region_sector doesn't match between 2 runs.

### PR DESCRIPTION
**Pull request by longshuicy**
SLC sector shock comparison was not showing correctly previously. Need to properly construct subKeys from region.

### CODE REVIEW

**Comment by ylyangtw** [comment]
Capital shock looks good, but when I switch to CGE, region Island is not rendering 
image
I only changed datawolf.config.js, do I need to change other configs?

**Review by Vismayak — APPROVED** [review]

**Comment by Vismayak** [comment]
@ylyangtw I got the same issue, I changed the other configs and refreshed and it worked for me
image

**Comment by ylyangtw** [comment]
> @ylyangtw I got the same issue, I changed the other configs and refreshed and it worked for me image

Ah thanks! Just changed everything and it works.

**Review by ylyangtw — APPROVED** [review]

**Comment by longshuicy** [comment]
> Capital shock looks good, but when I switch to CGE, region Island is not rendering image I only changed datawolf.config.js, do I need to change other configs?

Yes global.js is controling the regions. Galveston has island vs SLC has regions, the mismatch causing it to break.

**Pull request merged**
