### PR TITLE
Add support of earthquake tsunami hurricane and flood #44

### LINKED ISSUE #44: Add support of Earthquake, Tsunami, Hurricane and Flood
need to implement the RJSF first. There is one example on Galveston repo on bitbucket https://opensource.ncsa.illinois.edu/bitbucket/projects/INCORE1/repos/galveston-playbook/pull-requests/1/overview

### PR DESCRIPTION
**Pull request by longshuicy**
Add all hazards support: eq, tsunami, tornado, hurricane and flood

**To test locally:**
1. npm install
2. npm install react@~16.14.0 react-dom@~16.14.0 react-redux@~7.1.0 redux-thunk@~2.3.0 redux@~4.0.1 react-router-dom@~5.2.0 @material-ui/core@^4.11.0 @material-ui/icons@^4.9.1 babel-polyfill@^6.26.0 --no-save
3. export DEPLOY_ENV=development
4. npm run
You should be able to uncomment `map.config.js` to set the map bounding box to different area.

**To test in child repo:**
0. `yarn link` to register the incore-playbook
1. Go to Joplin repo and checkout the latest main branch: https://github.com/IN-CORE/Joplin-Playbook
2. npm install
3. `yarn link incore-playbook`
4. export DEPLOY_ENV=development
You should be able to set map configuration and allowed hazard types here: https://github.com/IN-CORE/Joplin-Playbook/blob/main/src/index.jsx

### CODE REVIEW

**Comment by longshuicy** [comment]
@navarroc @nunezco2 @diegoac2

**Comment by longshuicy** [comment]
Now also support model based EQ
image

**Comment by longshuicy** [comment]
@navarroc @diegoac2 @nunezco2 @ywkim312 @ncsa-mo please review

**Comment by navarroc** [comment]
For the model based EQ, we need to add the attenuation models. There is an /earthquakes/models endpoint to return all available models or we can add this to a configuration. Is adding the attenuation planned for later?

**Comment by longshuicy** [comment]
> For the model based EQ, we need to add the attenuation models. There is an /earthquakes/models endpoint to return all available models or we can add this to a configuration. Is adding the attenuation planned for later?

I removed it; but will add it back maybe in the next subsequent task

**Pull request merged**
